{
 "title": "WatchTower Overview",
 "tags": [ "watchtower" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Order Service Uptime %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://order-service:3001/health\"}[24h]) * 100"
    }
   ]
  },
  {
   "title": "Tracking Service Uptime %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://tracking-service:3002/health\"}[24h]) * 100"
    }
   ]
  },
  {
   "title": "Notification Service Uptime %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://notification-service:3003/health\"}[24h]) * 100"
    }
   ]
  }
 ]
}